### ISSUE TITLE
Error after clean build

### ISSUE THREAD

**Issue by mfranzke** [db-ux-design-system/core-web#1898]
### Which generators are impacted?

- [X] All
- [ ] HTML
- [ ] React
- [ ] Angular
- [ ] Vue
- [ ] Web components
- [ ] Power Apps

### Reproduction case

After doing a clean installation and build (`rm -r node_modules && npm run clean && npm i && npm run build && npm run build-showcases`), the following error comes up randomly:

```
> @db-ui/components@0.0.0 build:mitosis
> mitosis build

Could not replace Identifier with nothing.
Mitosis: angular: generated 28 components, 62 regular files.
Mitosis: vue3: generated 28 components, 62 regular files.
Mitosis: react: generated 28 components, 62 regular files.
Mitosis: webcomponent: generated 28 components, 62 regular files.
Mitosis: generation completed.

> @db-ui/components@0.0.0 build-components:directives
> cpr overrides/angular ../../output/angular -o


> @db-ui/components@0.0.0 build-components:docs
> react-docgen ../../output/react/src/components/**/*.tsx -o ../../output/docs.json -i *.spec.tsx


> @db-ui/components@0.0.0 build-components:post
> node scripts/post-build/index.js

SyntaxError: ****/output/react/src/components/tooltip/tooltip.tsx: Unterminated JSX contents. (45:22)

  43 |       ) : null}
  44 |
> 45 |       {props.children}
     |                       ^
  46 |    
    at constructor (****/node_modules/@babel/parser/lib/index.js:356:19)
    at TypeScriptParserMixin.raise (****/node_modules/@babel/parser/lib/index.js:3223:19)
    at TypeScriptParserMixin.jsxReadToken (*****/node_modules/@babel/parser/lib/index.js:6600:20)
    at TypeScriptParserMixin.getTokenFromCode (*****/node_modules/@babel/parser/lib/index.js:6942:12)
    at TypeScriptParserMixin.getTokenFromCode (*****/node_modules/@babel/parser/lib/index.js:9847:11)
    at TypeScriptParserMixin.nextToken (*****/node_modules/@babel/parser/lib/index.js:2347:10)
    at TypeScriptParserMixin.next (*****/node_modules/@babel/parser/lib/index.js:2258:10)
    at TypeScriptParserMixin.eat (*****/node_modules/@babel/parser/lib/index.js:2262:12)
    at TypeScriptParserMixin.expect (*****/node_modules/@babel/parser/lib/index.js:3585:10)
    at TypeScriptParserMixin.jsxParseExpressionContainer (*****/node_modules/@babel/parser/lib/index.js:6797:10)
    at TypeScriptParserMixin.jsxParseElementAt (*****/node_modules/@babel/parser/lib/index.js:6871:36)
    at TypeScriptParserMixin.jsxParseElement (*****/node_modules/@babel/parser/lib/index.js:6915:17)
    at TypeScriptParserMixin.parseExprAtom (*****/node_modules/@babel/parser/lib/index.js:6927:19)
    at TypeScriptParserMixin.parseExprSubscripts (*****/node_modules/@babel/parser/lib/index.js:10857:23)
    at TypeScriptParserMixin.parseUpdate (*****/node_modules/@babel/parser/lib/index.js:10840:21)
    at TypeScriptParserMixin.parseMaybeUnary (*****/node_modules/@babel/parser/lib/index.js:10816:23)
    at TypeScriptParserMixin.parseMaybeUnary (*****/node_modules/@babel/parser/lib/index.js:9696:18)
    at TypeScriptParserMixin.parseMaybeUnaryOrPrivate (*****/node_modules/@babel/parser/lib/index.js:10654:61)
    at TypeScriptParserMixin.parseExprOps (*****/node_modules/@babel/parser/lib/index.js:10659:23)
    at TypeScriptParserMixin.parseMaybeConditional (*****/node_modules/@babel/parser/lib/index.js:10636:23)
    at TypeScriptParserMixin.parseMaybeAssign (*****/node_modules/@babel/parser/lib/index.js:10597:21)
    at *****/node_modules/@babel/parser/lib/index.js:9632:39
    at TypeScriptParserMixin.tryParse (*****/node_modules/@babel/parser/lib/index.js:3592:20)
    at TypeScriptParserMixin.parseMaybeAssign (*****/node_modules/@babel/parser/lib/index.js:9632:18)
    at *****/node_modules/@babel/parser/lib/index.js:10567:39
    at TypeScriptParserMixin.allowInAnd (*****/node_modules/@babel/parser/lib/index.js:12284:12)
    at TypeScriptParserMixin.parseMaybeAssignAllowIn (*****/node_modules/@babel/parser/lib/index.js:10567:17)
    at TypeScriptParserMixin.parseParenAndDistinguishExpression (*****/node_modules/@babel/parser/lib/index.js:11499:28)
    at TypeScriptParserMixin.parseExprAtom (*****/node_modules/@babel/parser/lib/index.js:11137:23)
    at TypeScriptParserMixin.parseExprAtom (*****/node_modules/@babel/parser/lib/index.js:6932:20)
    at TypeScriptParserMixin.parseExprSubscripts (*****/node_modules/@babel/parser/lib/index.js:10857:23)
    at TypeScriptParserMixin.parseUpdate (*****/node_modules/@babel/parser/lib/index.js:10840:21)
    at TypeScriptParserMixin.parseMaybeUnary (*****/node_modules/@babel/parser/lib/index.js:10816:23)
    at TypeScriptParserMixin.parseMaybeUnary (*****/node_modules/@babel/parser/lib/index.js:9696:18)
    at TypeScriptParserMixin.parseMaybeUnaryOrPrivate (*****/node_modules/@babel/parser/lib/index.js:10654:61)
    at TypeScriptParserMixin.parseExprOps (*****/node_modules/@babel/parser/lib/index.js:10659:23)
    at TypeScriptParserMixin.parseMaybeConditional (*****/node_modules/@babel/parser/lib/index.js:10636:23)
    at TypeScriptParserMixin.parseMaybeAssign (*****/node_modules/@babel/parser/lib/index.js:10597:21)
    at TypeScriptParserMixin.parseMaybeAssign (*****/node_modules/@babel/parser/lib/index.js:9643:20)
    at TypeScriptParserMixin.parseExpressionBase (*****/node_modules/@babel/parser/lib/index.js:10551:23)
    at *****/node_modules/@babel/parser/lib/index.js:10547:39
    at TypeScriptParserMixin.allowInAnd (*****/node_modules/@babel/parser/lib/index.js:12279:16)
    at TypeScriptParserMixin.parseExpression (*****/node_modules/@babel/parser/lib/index.js:10547:17)
    at TypeScriptParserMixin.parseReturnStatement (*****/node_modules/@babel/parser/lib/index.js:13003:28)
    at TypeScriptParserMixin.parseStatementContent (*****/node_modules/@babel/parser/lib/index.js:12621:21)
    at TypeScriptParserMixin.parseStatementContent (*****/node_modules/@babel/parser/lib/index.js:9340:18)
    at TypeScriptParserMixin.parseStatementLike (*****/node_modules/@babel/parser/lib/index.js:12588:17)
    at TypeScriptParserMixin.parseStatementListItem (*****/node_modules/@babel/parser/lib/index.js:12568:17)
    at TypeScriptParserMixin.parseBlockOrModuleBlockBody (*****/node_modules/@babel/parser/lib/index.js:13189:61)
    at TypeScriptParserMixin.parseBlockBody (*****/node_modules/@babel/parser/lib/index.js:13182:10) {
  code: 'BABEL_PARSE_ERROR',
  reasonCode: 'UnterminatedJsxContent',
  syntaxPlugin: 'jsx',
  loc: Position { line: 45, column: 22, index: 1208 },
  pos: 1208
}
npm ERR! Lifecycle script `build-components:docs` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: @db-ui/components@0.0.0 
npm ERR!   at location: *****/packages/components 
ERROR: "build-components:docs" exited with 1.
npm ERR! Lifecycle script `build-components` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: @db-ui/components@0.0.0 
npm ERR!   at location: *****/packages/components 
ERROR: "build-components" exited with 1.
npm ERR! Lifecycle script `build` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: @db-ui/components@0.0.0 
npm ERR!   at location: *****/packages/components 
ERROR: "build:02_components" exited with 1.
```

### Expected Behaviour

The build runs smoothly.

### Screenshots

<img width="1624" alt="image" src="https://github.com/db-ui/mono/assets/787658/0eb7ec5c-9831-472d-af87-0c00743cfe2d">

### Browser version

None

**Comment by nmerget** [comment]
still an issue? @mfranzke

**Comment by nmerget** [comment]
closing this because of inactivity
